# Generated by Django 5.2.10 on 2026-02-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("total_count", models.IntegerField()),
                ("avg_pressure", models.FloatField()),
                ("avg_temp", models.FloatField()),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
