# Generated by Django 5.2.10 on 2026-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadhistory",
            options={},
        ),
        migrations.AddField(
            model_name="uploadhistory",
            name="avg_flowrate",
            field=models.FloatField(default=0.0),
        ),
    ]
